codegnan/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('codegnanapp.urls')),
    path('accounts/', include('registration.backends.default.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codegnanapp/urls.py
from django.urls import path
from codegnanapp.views import Index, PostCreate, details,like

app_name = 'codegnanapp'

urlpatterns = [
    path('', Index, name='index'),
    path('create/', PostCreate.as_view(), name='create'),
    path('details/<int:pk>', details, name='details'),
    path('ajax/likes/', like, name='like'),
]

codegnanapp/models.py
from django.db import models
from django.contrib.auth.models import User

"""if we are adding new feilds to the model we can write null = True , blank=True then we will not get this message
You are trying to add the field 'created_at' with 'auto_now_add=True' to post without a default; the database 
needs something to populate existing rows."""


class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # here i am creating meta class because i dont want this table to be created in the database
    class Meta:
        abstract = True


class Post(Timestamp):
    title = models.CharField(max_length=100, verbose_name='MovieName')
    description = models.TextField()
    image = models.ImageField(upload_to='')
    likes= models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Comment(Timestamp):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.comment

codegnanapp/forms.py
from django import forms
from codegnanapp.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

codegnanapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Post, Comment
from django.views.generic.edit import CreateView
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin as logindecorator
from django.contrib.auth.decorators import login_required
import datetime


# Create your views here.
def Index(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'index.html', context)


class PostCreate(logindecorator,CreateView):
    model = Post
    fields = ['title', 'description', 'image', ]
    template_name = 'create.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@login_required()
def details(request, pk):
    p = Post.objects.get(pk=pk)
    context = {'p': p}
    return render(request, 'detail.html', context)


def details(request, pk):
    p = Post.objects.get(pk=pk)
    comments = Comment.objects.filter(post_id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            c = Comment(post_id=pk, comment=comment, user=request.user)
            c.save()
            # return HttpResponseRedirect(reverse('codegnanapp:index'))
            return HttpResponseRedirect(reverse('codegnanapp:details', kwargs={'pk': pk}))

    else:
        form = CommentForm()
    return render(request, 'detail.html', {'form': form, 'p': p, 'comments': comments})


def like(request):
    if request.is_ajax():
        post_id = request.GET.get('post')
        post = Post.objects.get(id=post_id)
        post.likes += 1
        post.save()
        data = {'likes': post.likes}
    return JsonResponse(data)

codegnanapp/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  '
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-white bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'codegnanapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'codegnanapp:create' %}">Create</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
          {% if not user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;
        <a class="btn btn-success" href="{% url 'registration_register' %}">Register</a>
          {% else %}
          <a class="btn btn-warning" href="{% url 'auth_logout' %}">Logout</a>
          {% endif %}
      </li>
    </ul>
  </div>
        <span class="btn btn-danger text-uppercase">Hello, {{ request.user }}</span>
</nav> 
<div class="container-fluid">
    {% block content %}
    <!--content starts here -->
    {% endblock %}
</div>

</body>
</html>

codegnanapp/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}<br>
<html lang="">
    <head>
        <title>Create</title>
    </head>
<body>
<div class="container-fluid">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_ul}}
        <input class="btn btn-primary" type="submit" value="Save">
        </form>
</div>
</body>
</html>
{% endblock %}}

codegnanapp/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="https://kit.fontawesome.com/1a63e92af6.js" crossorigin="anonymous"></script>
<div class=" container">
    <div class="row">
        <div class="col-md-12"><br>
            <center><i><b>{{p.title}}</b></i></center><br>
        </div>
        <div class="col-md-8">
            {{p.description}}<br>
            <img src="{{p.image.url}}" height=" 300" width="300" alt="image">
        </div>
        <div class="col-md-4">
            <form action="" method="post">
                {% csrf_token %}
                {{form}}
                <input class="submit" type="submit" value="Submit">
            </form>
        </div>
    </div>
<span id="like">{{p.likes}}</span>
<button onclick="onClick()"><i class="fas fa-heart"></i></button>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
    function onClick(){
        $.ajax({
            url:"{% url 'codegnanapp:like' %}",
            data:{'post': {{p.id}}},
            success:function(data){
                	document.getElementById('like').innerHTML = data.likes

            }
        })
    }
</script>
    <div>
        <h6>Comments: <i class="fas fa-comment-alt"></i></h6>
        {% for i in comments %}
        {{forloop.counter}}-{{i.comment}}<br>
        {% endfor %}
</div>
</div>
{% endblock %}

codegnanapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
            {% for i in posts %}
            <div class = col-6><br>
                
                <a href="{% url 'codegnanapp:details' i.id %}">{{i.title}}</a><br>
                <img src="{{i.image.url}}" alt="" height="300px" width="450px"><br>
                {{i.timestamp}}<br>
                {{i.description}}<br>
                {{i.created_at}} by {{i.user}}<br>
                updated: {{i.updated_at}}
            </div>
            {% endfor %}
    </div>
</div>
{% endblock %}